Feature: As a user I should be able to use complex ion list features.
  Background:
    Given "I" navigate to "/lists/sortable"

  @watch
  Scenario: See list items (sanity check this time).
    Then "I" should see "//*[contains(., 'John Smith 1')]"
    Then "I" should see "//*[contains(., 'John Smith 2')]"
    Then "I" should see "//*[contains(., 'John Smith 3')]"
    Then "I" should see "//*[contains(., 'John Smith 4')]"
    Then "I" should see "//*[contains(., 'John Smith 5')]"
    Then "I" should see "//*[contains(., 'John Smith 6')]"
    Then "I" should see "//*[contains(., 'John Smith 7')]"
    Then "I" should see "//*[contains(., 'John Smith 8')]"
    Then "I" should see "//*[contains(., 'John Smith 9')]"
    Then "I" should see "//*[contains(., 'John Smith 10')]"
    Then "I" should see "//*[contains(., 'John Smith 11')]"
    Then "I" should see "//*[contains(., 'John Smith 12')]"
    Then "I" should see "//*[contains(., 'John Smith 13')]"
    Then "I" should see "//*[contains(., 'John Smith 14')]"
    Then "I" should see "//*[contains(., 'John Smith 15')]"
    Then "I" should see "//*[contains(., 'John Smith 16')]"
    Then "I" should see "//*[contains(., 'John Smith 17')]"
    Then "I" should see "//*[contains(., 'John Smith 18')]"
    Then "I" should see "//*[contains(., 'John Smith 19')]"
    Then "I" should see "//*[contains(., 'John Smith 20')]"

  @watch
  Scenario: Reorder arbitrary items around.
    And "I" drag "//div[contains(@class, 'item')][1]/*[contains(., 'John Smith 1')]" to "//div[contains(@class, 'item')][2]/*[contains(., 'John Smith 2')]"
    Then "I" should see "//div[contains(@class, 'item')][1]/*[contains(., 'John Smith 2')]"
    Then "I" should see "//div[contains(@class, 'item')][2]/*[contains(., 'John Smith 1')]"
    Then "I" should see "//div[contains(@class, 'item')][3]/*[contains(., 'John Smith 3')]"
    Then "I" should see "//div[contains(@class, 'item')][4]/*[contains(., 'John Smith 4')]"
    Then "I" should see "//div[contains(@class, 'item')][5]/*[contains(., 'John Smith 5')]"
    Then "I" should see "//div[contains(@class, 'item')][6]/*[contains(., 'John Smith 6')]"
    Then "I" should see "//div[contains(@class, 'item')][7]/*[contains(., 'John Smith 7')]"
    Then "I" should see "//div[contains(@class, 'item')][8]/*[contains(., 'John Smith 8')]"
    Then "I" should see "//div[contains(@class, 'item')][9]/*[contains(., 'John Smith 9')]"
    Then "I" should see "//div[contains(@class, 'item')][10]/*[contains(., 'John Smith 10')]"
    Then "I" should see "//div[contains(@class, 'item')][11]/*[contains(., 'John Smith 11')]"
    Then "I" should see "//div[contains(@class, 'item')][12]/*[contains(., 'John Smith 12')]"

    And "I" drag "//div[contains(@class, 'item')][5]/*[contains(., 'John Smith 5')]" to "//div[contains(@class, 'item')][9]/*[contains(., 'John Smith 9')]"
    Then "I" should see "//div[contains(@class, 'item')][1]/*[contains(., 'John Smith 2')]"
    Then "I" should see "//div[contains(@class, 'item')][2]/*[contains(., 'John Smith 1')]"
    Then "I" should see "//div[contains(@class, 'item')][3]/*[contains(., 'John Smith 3')]"
    Then "I" should see "//div[contains(@class, 'item')][4]/*[contains(., 'John Smith 4')]"
    Then "I" should see "//div[contains(@class, 'item')][5]/*[contains(., 'John Smith 6')]"
    Then "I" should see "//div[contains(@class, 'item')][6]/*[contains(., 'John Smith 7')]"
    Then "I" should see "//div[contains(@class, 'item')][7]/*[contains(., 'John Smith 8')]"
    Then "I" should see "//div[contains(@class, 'item')][8]/*[contains(., 'John Smith 9')]"
    Then "I" should see "//div[contains(@class, 'item')][9]/*[contains(., 'John Smith 5')]"
    Then "I" should see "//div[contains(@class, 'item')][10]/*[contains(., 'John Smith 10')]"
    Then "I" should see "//div[contains(@class, 'item')][11]/*[contains(., 'John Smith 11')]"
    Then "I" should see "//div[contains(@class, 'item')][12]/*[contains(., 'John Smith 12')]"

    And "I" drag "//div[contains(@class, 'item')][1]/*[contains(., 'John Smith 2')]" to "//div[contains(@class, 'item')][2]/*[contains(., 'John Smith 1')]"
    Then "I" should see "//div[contains(@class, 'item')][1]/*[contains(., 'John Smith 1')]"
    Then "I" should see "//div[contains(@class, 'item')][2]/*[contains(., 'John Smith 2')]"
    Then "I" should see "//div[contains(@class, 'item')][3]/*[contains(., 'John Smith 3')]"
    Then "I" should see "//div[contains(@class, 'item')][4]/*[contains(., 'John Smith 4')]"
    Then "I" should see "//div[contains(@class, 'item')][5]/*[contains(., 'John Smith 6')]"
    Then "I" should see "//div[contains(@class, 'item')][6]/*[contains(., 'John Smith 7')]"
    Then "I" should see "//div[contains(@class, 'item')][7]/*[contains(., 'John Smith 8')]"
    Then "I" should see "//div[contains(@class, 'item')][8]/*[contains(., 'John Smith 9')]"
    Then "I" should see "//div[contains(@class, 'item')][9]/*[contains(., 'John Smith 5')]"
    Then "I" should see "//div[contains(@class, 'item')][10]/*[contains(., 'John Smith 10')]"
    Then "I" should see "//div[contains(@class, 'item')][11]/*[contains(., 'John Smith 11')]"
    Then "I" should see "//div[contains(@class, 'item')][12]/*[contains(., 'John Smith 12')]"
